force-app/main/default/objects/TNCar__c/TNCar__c.object-meta.xml
<CustomObject>
    <label>TN Car</label>
    <nameField>
        <displayFormat>TNC-{0000}</displayFormat>
        <label>TN Car</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TN Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TNCar__c/fields/TNCarCountry__c.field-meta.xml
<CustomField>
    <fullName>TNCarCountry__c</fullName>
    <label>TN Car Country</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TNCar__c/fields/TNCarLicence__c.field-meta.xml
<CustomField>
    <fullName>TNCarLicence__c</fullName>
    <externalId>true</externalId>
    <label>TN Car Licence</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TNCar__c/fields/TNCarType__c.field-meta.xml
<CustomField>
    <fullName>TNCarType__c</fullName>
    <label>TN Car Type</label>
    <referenceTo>TNCarType__c</referenceTo>
    <relationshipLabel>TN Cars</relationshipLabel>
    <relationshipName>TN_Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TNCarSales__c/TNCarSales__c.object-meta.xml
<CustomObject>
    <label>TN Car Sales</label>
    <nameField>
        <displayFormat>TNCS-{0000}</displayFormat>
        <label>TN Car Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TN Car Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TNCarSales__c/fields/TNCar__c.field-meta.xml
<CustomField>
    <fullName>TNCar__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TN Car</label>
    <referenceTo>TNCar__c</referenceTo>
    <relationshipLabel>TN Car Sales</relationshipLabel>
    <relationshipName>TNCarSales</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TNCarSales__c/fields/TNCarLicence__c.field-meta.xml
<CustomField>
    <fullName>TNCarLicence__c</fullName>
    <formula>TNCar__r.TNCarLicence__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TN Car Licence</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TNCarSales__c/fields/TNCarType__c.field-meta.xml
<CustomField>
    <fullName>TNCarType__c</fullName>
    <formula>TNCar__r.TNCarType__r.externalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TN Car Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TNCarSales__c/fields/TNDate__c.field-meta.xml
<CustomField>
    <fullName>TNDate__c</fullName>
    <label>TN Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TNCarSales__c/fields/TNModel__c.field-meta.xml
<CustomField>
    <fullName>TNModel__c</fullName>
    <formula>TNCar__r.TNCarType__r.TNModel__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TN Model</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TNCarSales__c/fields/TNPrice__c.field-meta.xml
<CustomField>
    <fullName>TNPrice__c</fullName>
    <label>TN Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TNCarSales__c/fields/TNType__c.field-meta.xml
<CustomField>
    <fullName>TNType__c</fullName>
    <formula>TEXT(TNCar__r.TNCarType__r.TNBodyStyle__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TN Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TNCarType__c/TNCarType__c.object-meta.xml
<CustomObject>
    <label>TNCarType</label>
    <nameField>
        <displayFormat>TNCT-{000000}</displayFormat>
        <label>TNCarType Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TNCarTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TNCarType__c/fields/externalId__c.field-meta.xml
<CustomField>
    <fullName>externalId__c</fullName>
    <externalId>true</externalId>
    <label>externalId</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TNCarType__c/fields/TNBodyStyle__c.field-meta.xml
<CustomField>
    <fullName>TNBodyStyle__c</fullName>
    <label>TN Body Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>Convertible</fullName>
            </value>
            <value>
                <fullName>Coupe</fullName>
            </value>
            <value>
                <fullName>Wagon</fullName>
            </value>
            <value>
                <fullName>Van/Minivan</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TNCarType__c/fields/TNCarBrand__c.field-meta.xml
<CustomField>
    <fullName>TNCarBrand__c</fullName>
    <label>TN Car Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acura</fullName>
            </value>
            <value>
                <fullName>Alfa Romeo</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Bentley</fullName>
            </value>
            <value>
                <fullName>Buick</fullName>
            </value>
            <value>
                <fullName>Cadillac</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Chrysler</fullName>
            </value>
            <value>
                <fullName>Dodge</fullName>
            </value>
            <value>
                <fullName>Fiat</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>GMC</fullName>
            </value>
            <value>
                <fullName>Genesis</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Infiniti</fullName>
            </value>
            <value>
                <fullName>Jaguar</fullName>
            </value>
            <value>
                <fullName>Jeep</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Land Rover</fullName>
            </value>
            <value>
                <fullName>Lexus</fullName>
            </value>
            <value>
                <fullName>Lincoln</fullName>
            </value>
            <value>
                <fullName>Lotus</fullName>
            </value>
            <value>
                <fullName>Maserati</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Mercury</fullName>
            </value>
            <value>
                <fullName>Mini</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TNCarType__c/fields/TNModel__c.field-meta.xml
<CustomField>
    <fullName>TNModel__c</fullName>
    <label>TNModel</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CodeReviewTest.cls
@isTest
public with sharing class CodeReviewTest {
	private static List<String> bodyStyles = new List<String>{'Sedan', 'Convertible'};
	private static List<String> brands = new List<String>{'Chevrolet', 'Fiat'};
	private static List<String> models = new List<String>{'Blazer', '500L'};
	private static List<String> countries = new List<String>{'Japan', 'Italy', 'USA', 'South Korea', 'England'};
	private static TNController.DataFromCarType comparator1;
	private static TNController.DataFromCarType comparator2;
	private static String carType1Id;
	private static String carType2Id;
    @TestSetup
	static void makeData() {
		List<TNCarType__c> carTypes = new List<TNCarType__c>();
		for (Integer i = 0; i < 2; i++) {
			TNCarType__c carType= new TNCarType__c (
				externalId__c = String.valueOf(i + 1),
				TNBodyStyle__c = bodyStyles[i],
				TNCarBrand__c = brands[i],
				TNModel__c = models[i]
			);
			carTypes.add(carType);
		}
		insert carTypes;
		carType1Id = carTypes[0].Id;
		carType2Id = carTypes[1].Id;
		List<TNCar__c> cars = new List<TNCar__c>();
		for (Integer i = 0; i < 10; i++) {
			TNCar__c car = new TNCar__c (
				TNCarLicence__c = '000' + String.valueOf(i),
				TNCarCountry__c = i < 5 ? countries[i] : countries[i-5],
				TNCarType__c = i < 2 ? carTypes[i].Id : carTypes[Math.mod(i, 2)].Id
			);
			cars.add(car);
		}
		insert cars;
		List<TNCarSales__c> sales = new List<TNCarSales__c>();
		for (Integer i = 0; i < 50; i++) {
			TNCarSales__c sale = new TNCarSales__c (
				TNCar__c = i < 10 ? cars[i].Id : cars[Math.mod(i, 10)].Id,
				TNPrice__c = 90000*Math.random() + 10000,
				TNDate__c = getRandomDate()
			);
			sales.add(sale);
		}
		insert sales;
		sales = [SELECT TNType__c, TNDate__c, TNPrice__c, TNCarLicence__c FROM TNCarSales__c];
		List<TNCarSales__c> toCompare1 = new List<TNCarSales__c>();
		List<TNCarSales__c> toCompare2 = new List<TNCarSales__c>();
		for (TNCarSales__c sale : sales) {
			if (sale.TNType__c == '1') {toCompare1.add(sale);}
			else {toCompare2.add(sale);}
		}
		comparator1 = new TNController.DataFromCarType(toCompare1);
		comparator2 = new TNController.DataFromCarType(toCompare2);
	}
	@isTest
	private static void returnDataFromType1 () {
		TNController.DataFromCarType data = TNController.getSalesDataFromCarType(carType1Id);
		System.assertEquals(comparator1.moreExpensiveDate, data.moreExpensiveDate, 'The dates must be the same');
		System.assertEquals(comparator1.moreExpensiveLicense, data.moreExpensiveLicense, 'The licences must be the same');
		System.assertEquals(comparator1.moreExpensiveSalePrice, data.moreExpensiveSalePrice, 'The prices must be the same');
		System.assertEquals(comparator1.totalQuantity, data.totalQuantity, 'The quantity must be the same');
		System.assertEquals(comparator1.totalMoneyRaised, data.totalMoneyRaised, 'The money must be the same');
	}
	@isTest
	private static void returnDataFromType2 () {
		TNController.DataFromCarType data = TNController.getSalesDataFromCarType(carType2Id);
		System.assertEquals(comparator2.moreExpensiveDate, data.moreExpensiveDate, 'The dates must be the same');
		System.assertEquals(comparator2.moreExpensiveLicense, data.moreExpensiveLicense, 'The licences must be the same');
		System.assertEquals(comparator2.moreExpensiveSalePrice, data.moreExpensiveSalePrice, 'The prices must be the same');
		System.assertEquals(comparator2.totalQuantity, data.totalQuantity, 'The quantity must be the same');
		System.assertEquals(comparator2.totalMoneyRaised, data.totalMoneyRaised, 'The money must be the same');
	}
	/** Utils */
	private static Date getRandomDate () {
		Integer month = Integer.valueOf(Math.random()*11) + 1;
		Integer day = Integer.valueOf(Math.random()*27) + 1;
		return Date.newInstance(Date.today().year()-1, month, day);
	}
}