force-app/main/default/objects/TNCarSales__c/TNCarSales__c.object-meta.xml
<CustomObject>
    <label>TN Car Sales</label>
    <nameField>
        <displayFormat>TNCS-{0000}</displayFormat>
        <label>TN Car Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TN Car Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TNCarSales__c/fields/TNCarLicence__c.field-meta.xml
<CustomField>
    <fullName>TNCarLicence__c</fullName>
    <formula>TNCar__r.TNCarLicence__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TN Car Licence</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TNCarSales__c/fields/TNDate__c.field-meta.xml
<CustomField>
    <fullName>TNDate__c</fullName>
    <label>TN Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TNCarSales__c/fields/TNPrice__c.field-meta.xml
<CustomField>
    <fullName>TNPrice__c</fullName>
    <label>TN Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TNController.cls
public class TNController {
	@AuraEnabled
	public static DataFromCarType getSalesDataFromCarType(String Id) {
		return new DataFromCarType(new List<TNCarSales__c>());
	}
	public class DataFromCarType {
		@AuraEnabled public List<TNCarSales__c> sales;
		@AuraEnabled public Integer totalQuantity;
		@AuraEnabled public Double totalMoneyRaised;
		@AuraEnabled public Date moreExpensiveDate;
		@AuraEnabled public String moreExpensiveLicense;
		@AuraEnabled public Double moreExpensiveSalePrice;
		public DataFromCarType(List<TNCarSales__c> sales) {
			this.sales = sales;
			this.totalQuantity = 0;
			this.totalMoneyRaised = 0;
			for (TNCarSales__c sale : sales) {
				this.totalQuantity += 1;
				this.totalMoneyRaised += sale.TNPrice__c;
				if (this.moreExpensiveSalePrice < sale.TNPrice__c) {
					this.moreExpensiveSalePrice = sale.TNPrice__c;
					this.moreExpensiveLicense = sale.TNCarLicence__c;
					this.moreExpensiveDate = sale.TNDate__c;
				}
			}
		}
	}
}